OBJS=${OBJS_DIR}/auth.o ${OBJS_DIR}/main.o ${OBJS_DIR}/linked_list.o

${OBJS_DIR}/auth.o: auth.c
	${GCC} ${FLAGS} -c auth.c -o $@

${OBJS_DIR}/linked_list.o: linked_list.c
	${GCC} ${FLAGS} -c linked_list.c -o $@

${OBJS_DIR}/main.o: main.c
	${GCC} ${FLAGS} -c main.c -o $@